name: Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      TEST_USER: ${{ secrets.TEST_USER }}
      TEST_PASS: ${{ secrets.TEST_PASS }}

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Optional: Start your server if needed
      # If you have a local server, e.g., npm start
      # - name: Start server
      #   run: npm start &
      #   env:
      #     NODE_ENV: test
      # Wait a few seconds for server to start:
      # - run: sleep 5

      # 5️⃣ Run UI & API tests
      - name: Run tests
        run: npm run test:ui && npm run test:api

      # 6️⃣ (Optional) Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
